services:
  db:
    image: postgres
    container_name: budget_db_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: budget
    ports:
      - 5432:5432
    volumes:
      - budget_pg_data:/var/lib/postgresql/data

volumes:
  budget_pg_data: